# Comfy Desktop: append portable model paths to extra_models_config.yaml
# Usage:
#   powershell -ExecutionPolicy Bypass -File tools/link_comfy_desktop_models.ps1 -PortableRoot "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI"
#   ... -Apply   # backup + append

param(
    [string]$PortableRoot = "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI",
    [switch]$Apply
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $PortableRoot)) {
    Write-Host "PortableRoot not found: $PortableRoot" -ForegroundColor Red
    Write-Host "Pass your real ComfyUI folder that contains 'models'."
    exit 1
}

$models = Join-Path $PortableRoot "models"
if (-not (Test-Path $models)) {
    Write-Host "No models folder under: $PortableRoot" -ForegroundColor Red
    exit 1
}

# Normalize to absolute path with backslashes for YAML
$root = (Resolve-Path $PortableRoot).Path
if (-not $root.EndsWith("\")) { $root = $root + "\" }

$fragment = @"

# ===== portable_shared (generated by link_comfy_desktop_models.ps1) =====
portable_shared:
    base_path: $root
    checkpoints: models/checkpoints/
    loras: models/loras/
    vae: models/vae/
    text_encoders: models/text_encoders/
    diffusion_models: models/diffusion_models/
    unet: models/unet/
    clip: models/clip/
    clip_vision: models/clip_vision/
    controlnet: models/controlnet/
    upscale_models: models/upscale_models/
    embeddings: models/embeddings/
    hypernetworks: models/hypernetworks/
"@

Write-Host "==== YAML fragment ===="
Write-Host $fragment

$configDir = Join-Path $env:APPDATA "ComfyUI"
$configPath = Join-Path $configDir "extra_models_config.yaml"

if (-not $Apply) {
    Write-Host ""
    Write-Host "Dry-run only. Re-run with -Apply to backup and append to:" -ForegroundColor Yellow
    Write-Host "  $configPath"
    exit 0
}

if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

if (Test-Path $configPath) {
    $stamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $backup = Join-Path $configDir "extra_models_config.backup_$stamp.yaml"
    Copy-Item $configPath $backup
    Write-Host "Backup: $backup" -ForegroundColor Green
    $existing = Get-Content -Raw -Path $configPath
    if ($existing -match "portable_shared:") {
        Write-Host "portable_shared already present. Not appending again." -ForegroundColor Yellow
        exit 0
    }
    Add-Content -Path $configPath -Value $fragment -Encoding UTF8
} else {
    Set-Content -Path $configPath -Value $fragment.TrimStart() -Encoding UTF8
    Write-Host "Created new config: $configPath" -ForegroundColor Green
}

Write-Host "Done. Fully quit and restart Comfy Desktop." -ForegroundColor Green
